// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serve.protos

package Tserve

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the protos package it is being compiled against.
// A compilation error at this line likely means your copy of the
// protos package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the protos package

//请求注册服务
type ReqRegService struct {
	ServerId             int32    `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	SvrType              int32    `protobuf:"varint,2,opt,name=svrType,proto3" json:"svrType,omitempty"`
	Host                 string   `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRegService) Reset()         { *m = ReqRegService{} }
func (m *ReqRegService) String() string { return proto.CompactTextString(m) }
func (*ReqRegService) ProtoMessage()    {}
func (*ReqRegService) Descriptor() ([]byte, []int) {
	return fileDescriptor_7edf7f5b739891d6, []int{0}
}

func (m *ReqRegService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRegService.Unmarshal(m, b)
}
func (m *ReqRegService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRegService.Marshal(b, m, deterministic)
}
func (m *ReqRegService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRegService.Merge(m, src)
}
func (m *ReqRegService) XXX_Size() int {
	return xxx_messageInfo_ReqRegService.Size(m)
}
func (m *ReqRegService) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRegService.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRegService proto.InternalMessageInfo

func (m *ReqRegService) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *ReqRegService) GetSvrType() int32 {
	if m != nil {
		return m.SvrType
	}
	return 0
}

func (m *ReqRegService) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ReqRegService) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

//响应注册服务
type AckRegService struct {
	Result               int32    `protobuf:"zigzag32,1,opt,name=result,proto3" json:"result,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckRegService) Reset()         { *m = AckRegService{} }
func (m *AckRegService) String() string { return proto.CompactTextString(m) }
func (*AckRegService) ProtoMessage()    {}
func (*AckRegService) Descriptor() ([]byte, []int) {
	return fileDescriptor_7edf7f5b739891d6, []int{1}
}

func (m *AckRegService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckRegService.Unmarshal(m, b)
}
func (m *AckRegService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckRegService.Marshal(b, m, deterministic)
}
func (m *AckRegService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckRegService.Merge(m, src)
}
func (m *AckRegService) XXX_Size() int {
	return xxx_messageInfo_AckRegService.Size(m)
}
func (m *AckRegService) XXX_DiscardUnknown() {
	xxx_messageInfo_AckRegService.DiscardUnknown(m)
}

var xxx_messageInfo_AckRegService proto.InternalMessageInfo

func (m *AckRegService) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *AckRegService) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqRegService)(nil), "Tserve.ReqRegService")
	proto.RegisterType((*AckRegService)(nil), "Tserve.AckRegService")
}

func init() { proto.RegisterFile("serve.protos", fileDescriptor_7edf7f5b739891d6) }

var fileDescriptor_7edf7f5b739891d6 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x86, 0x89, 0xd6, 0x68, 0x4f, 0x3a, 0x98, 0x41, 0x82, 0x53, 0xe9, 0xd4, 0xc9, 0xc5, 0x07,
	0x10, 0x47, 0xd7, 0xb3, 0x4f, 0x60, 0x3d, 0xaa, 0x68, 0x49, 0xbc, 0xc4, 0x80, 0x6f, 0x2f, 0x3d,
	0xaa, 0xb8, 0xfd, 0xdf, 0xff, 0x1f, 0x7c, 0x07, 0xcb, 0x40, 0x9c, 0x68, 0xeb, 0xd9, 0x45, 0x67,
	0x74, 0x23, 0x54, 0xf5, 0x50, 0x20, 0x3d, 0x91, 0xba, 0x13, 0x71, 0xba, 0xb5, 0x64, 0x36, 0xb0,
	0x90, 0x85, 0x8f, 0x17, 0xab, 0x4a, 0x55, 0xcf, 0xf0, 0xc7, 0xc6, 0xc2, 0x3c, 0x24, 0x6e, 0xde,
	0x9e, 0xec, 0x44, 0xa6, 0x2f, 0x1a, 0x03, 0xd9, 0xd5, 0x85, 0x68, 0xa7, 0xa5, 0xaa, 0x73, 0x94,
	0x3c, 0x74, 0xde, 0x71, 0xb4, 0x99, 0x9c, 0x4a, 0xae, 0xf6, 0x50, 0x1c, 0xda, 0xfb, 0x9f, 0x6e,
	0x0d, 0x9a, 0x29, 0xbc, 0x1e, 0x51, 0x64, 0x2b, 0x1c, 0x69, 0xe8, 0x89, 0xb9, 0x0f, 0x9d, 0x98,
	0x72, 0x1c, 0xe9, 0xac, 0xe5, 0xfd, 0xdd, 0x27, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xc8, 0xd3, 0x2a,
	0xcd, 0x00, 0x00, 0x00,
}
